import type { UiLocale } from "../../shared/localization.mjs";
import { useState } from "react";
import { getSabrinaDesktop } from "../lib/sabrina-desktop";
import { useChatCommands } from "../commands/useChatCommands";
import { useBrowserCommands } from "../commands/useBrowserCommands";
import { useDesktopDiagnostics } from "../application/use-desktop-diagnostics";
import { useOpenClawState } from "../state/useOpenClawState";
import { useBrowserState } from "../state/useBrowserState";
import { useGenTabSourceState } from "../state/useGenTabSourceState";
import { useThreadState } from "../state/useThreadState";
import { useThreadComposerState } from "../state/useThreadComposerState";
import { useGenTabController } from "./useGenTabController";

export function useAppController(uiLocale: UiLocale) {
  const desktop = getSabrinaDesktop();
  const {
    tabs,
    activeTab,
    historyEntries,
    bookmarkEntries,
    downloads,
    windowState,
    desktopUnavailable,
    isMacDesktop,
    supportsNativeBrowserMenu,
  } = useBrowserState(desktop);
  const {
    binding,
    connectionConfig,
    connectionState,
    bindingSetupState,
    beginBindingSetup,
    connectOpenClaw,
    createRelayConnectCode,
    disconnectOpenClaw,
    doctorOpenClaw,
    probeConnection,
    getRelayPairingState,
    saveConnectionPreset,
    removeSavedConnection,
    selectSavedConnection,
    connectSavedConnection,
    setBindingTarget,
    skillCatalog,
    gatewayStatus,
    deviceStatus,
    pairingStatus,
    savedConnections,
    activeConnectionId,
    lastError,
    doctorReport,
    connectionProbe,
    selectedModel,
    modelOptions,
    turnJournalEntries,
    turnJournalStats,
    browserMemoryRecords,
    browserMemoryStats,
    isModelSwitching,
    approvingPairingRequestId,
    isApprovingLatestDevice,
    switchSelectedModel,
    approvePairingRequest,
    approveLatestDeviceRequest,
  } = useOpenClawState(desktop);
  const {
    diagnostics,
    refreshDiagnostics: refreshDesktopDiagnostics,
    openLogDirectory,
    revealHumanLogFile,
  } = useDesktopDiagnostics(desktop);
  const {
    activeMessages,
    activeThreadId,
    appendMessage,
    selectThread,
    threadSummaries,
  } = useThreadState({
    desktop,
    tabs,
    activeTab,
    uiLocale,
  });
  const {
    composerText,
    isThinking,
    referenceCandidates,
    referenceQuery,
    selectedComposerSkill,
    selectedReferenceIds,
    clearSelectedComposerSkill,
    clearSelectedReferences,
    setComposerText,
    setPending,
    setReferenceQuery,
    setSelectedComposerSkill,
    toggleReference,
  } = useThreadComposerState({
    tabs,
    activeTab,
    activeThreadId,
  });
  const {
    primarySourceTab: primaryGenTabSourceTab,
    readyReferenceTabs,
    totalSourcePageCount: totalGenTabSourcePageCount,
    canGenerate: canGenerateGenTab,
    blockedReason: genTabBlockedReason,
  } = useGenTabSourceState({
    tabs,
    activeTab,
    selectedReferenceIds,
  });
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const {
    generatingGenTabId,
    handleOpenGenTabGenerator,
    handleOpenCodingGenTabGenerator,
    handleCloseGenTab,
  } = useGenTabController({
    activeTabId: activeTab?.tabId ?? null,
    binding,
    composerText,
    selectedReferenceIds: readyReferenceTabs.map((tab) => tab.id),
  });
  const isBookmarked = activeTab
    ? bookmarkEntries.some((bookmark) => bookmark.url === activeTab.url)
    : false;
  const desktopActions = useBrowserCommands({
    desktop,
    activeTab,
    refreshDiagnostics: refreshDesktopDiagnostics,
  });
  const aiChatActions = useChatCommands({
    desktop,
    activeTab,
    activeThreadId,
    binding,
    uiLocale,
    selectedModel,
    isModelSwitching,
    composerText,
    selectedReferenceIds,
    selectedComposerSkill,
    appendMessage,
    clearSelectedReferences,
    clearSelectedComposerSkill,
    setComposerText,
    setPending,
    switchSelectedModel,
  });

  return {
    binding,
    connectionConfig,
    connectionState,
    bindingSetupState,
    skillCatalog,
    gatewayStatus,
    deviceStatus,
    pairingStatus,
    savedConnections,
    activeConnectionId,
    lastError,
    doctorReport,
    connectionProbe,
    activeThreadId,
    tabs,
    activeTab,
    activeMessages,
    threadSummaries,
    referenceCandidates,
    referenceQuery,
    selectedComposerSkill,
    selectedReferenceIds,
    primaryGenTabSourceTab,
    totalGenTabSourcePageCount,
    canGenerateGenTab,
    genTabBlockedReason,
    historyEntries,
    bookmarkEntries,
    downloads,
    diagnostics,
    composerText,
    selectedModel,
    modelOptions,
    turnJournalEntries,
    turnJournalStats,
    browserMemoryRecords,
    browserMemoryStats,
    windowState,
    isMacDesktop,
    supportsNativeBrowserMenu,
    sidebarOpen,
    isThinking,
    isModelSwitching,
    approvingPairingRequestId,
    isApprovingLatestDevice,
    isBookmarked,
    desktopUnavailable,
    beginBindingSetup,
    connectOpenClaw,
    createRelayConnectCode,
    disconnectOpenClaw,
    doctorOpenClaw,
    probeConnection,
    getRelayPairingState,
    saveConnectionPreset,
    removeSavedConnection,
    selectSavedConnection,
    connectSavedConnection,
    approvePairingRequest,
    approveLatestDeviceRequest,
    setSidebarOpen,
    setBindingTarget,
    setComposerText,
    setSelectedComposerSkill,
    setReferenceQuery,
    clearSelectedComposerSkill,
    clearSelectedReferences,
    selectThread,
    toggleReference,
    generatingGenTabId,
    handleOpenGenTabGenerator,
    handleOpenCodingGenTabGenerator,
    handleCloseGenTab,
    ...aiChatActions,
    ...desktopActions,
    openLogDirectory,
    revealHumanLogFile,
  };
}
